repositories:
 - name: podinfo
   url: https://stefanprodan.github.io/podinfo

releases:
- name: podinfo
  namespace: default
  chart: podinfo/podinfo
- name: podinfo2
  namespace: default
  chart: podinfo/podinfo