image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.5.4

# UI customization to display secret
ui:
  message: "Encrypted secret will be shown below"
  color: "#34577c"

# Inject secret as environment variable
env:
  - name: SECRET_MESSAGE
    valueFrom:
      secretKeyRef:
        name: hello-world-secret
        key: message
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: hello-world-secret
        key: api_key
