apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: all-apps
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        revision: HEAD
        directories:
          - path: apps/*/overlays/*
  template:
    metadata:
      name: '{{path[3]}}-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        targetRevision: HEAD
        path: '{{path}}'
        kustomize:
          namespace: '{{path[3]}}-{{path[1]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}-{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
