apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
spec:
  description: Production environment applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'prod-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
spec:
  description: Staging environment applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'staging-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
