apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # GitHub service configuration (using PAT)
  service.github: |
    token: $github-token

  # Trigger when deployment is successful and healthy
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.sync.revision
      send: [pr-deployment-success]

  # Trigger when deployment fails or becomes unhealthy
  trigger.on-deployment-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed'] or app.status.health.status == 'Degraded'
      oncePer: app.status.sync.revision
      send: [pr-deployment-failure]

  # Template for successful deployment check
  template.pr-deployment-success: |
    message: |
      Application {{.app.metadata.name}} deployed successfully to staging
      Sync Status: {{.app.status.sync.status}}
      Health: {{.app.status.health.status}}
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.sync.revision}}"
      checkRun:
        status: completed
        conclusion: success
        name: "staging-deployment/{{.app.metadata.labels.app-name}}"
        output:
          title: "Staging deployment successful ✅"
          summary: "Application {{.app.metadata.name}} deployed successfully to staging"
          text: |
            **Sync Status:** {{.app.status.sync.status}}
            **Health Status:** {{.app.status.health.status}}
            **Sync Revision:** {{.app.status.sync.revision}}

            The application has been successfully deployed and is healthy in the staging environment.

  # Template for failed deployment check
  template.pr-deployment-failure: |
    message: |
      Application {{.app.metadata.name}} failed to deploy to staging
      Sync Status: {{.app.status.sync.status}}
      Health: {{.app.status.health.status}}
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.sync.revision}}"
      checkRun:
        status: completed
        conclusion: failure
        name: "staging-deployment/{{.app.metadata.labels.app-name}}"
        output:
          title: "Staging deployment failed ❌"
          summary: "Application {{.app.metadata.name}} failed to deploy to staging"
          text: |
            **Sync Status:** {{.app.status.sync.status}}
            **Health Status:** {{.app.status.health.status}}
            **Sync Revision:** {{.app.status.sync.revision}}

            The application deployment or health check failed in the staging environment.
