apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
type: Opaque
stringData:
    github-token: ENC[AES256_GCM,data:0rZoF7N3DcEs1c9+8h7ofy6hM4p1OriaijIEFiqggvEBI0iD2TxwsA==,iv:yhtAc3aP7bckpu9ttR3n/O9nCD0AMa2hJjDug1ij3T4=,tag:6bjzzF90eJcbbjbDxm51jA==,type:str]
sops:
    age:
        - recipient: age1u39s0c70ny5tjvvgvgj0jdw6ejxzs0t93k2tl0czmvjczt64yvjst7rkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N3k0ZXdJcFlXYzVHWFFi
            bUxIZ1VaS2E4cXFPMkljM3pXdzk1Wm1LQ1djCm1VUVd5UlpNS3lsQVJSaExmdGRq
            REp6ek5yZ1g2eUJPajVmWFR4Q2FlaEkKLS0tIGtpLzFsQmdaZlpLK2tEQ0phK2Fi
            a0NRNWUzcDNsUW15OFozMzV3S2pkdk0KbFoON2pOKyb+d4axKBc7jmQ5CAFFGt3m
            JzCbul5Srr3xARPy/5YjFU3KhT6D+QlmZI/gyKWcrT90IykIbP7ELA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T11:37:12Z"
    mac: ENC[AES256_GCM,data:cAQLWoOELQUWyDR/tLzn1JWeDMxtMLmtnoQNN46ecu7RFGWpYo/QHdnG8SJcRNrWKfmjtSXHfv8iJVD0iDUv2oYBh8s7NWVfXR+OBg5dXQaOlrkY6f/orMs3Uy7Pst8Er+IKH3C6aBmjrcJMHbQThd6QCdQmasooSsPnsicypQQ=,iv:SXEBmC782TX383l7mzeuzT8EAG9sa5f7KMR8IjzZBE0=,tag:g0wua3l9D2Z7Wt013jEOYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
