apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: notifications-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - notifications-secret.enc.yaml
