apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: hello-world-2-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secret.enc.yaml
