apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
generators:
  - secret-generator.yaml

patches:
  - target:
      kind: Kustomization
    patch: |-
      - op: replace
        path: /helmCharts/0/version
        value: 6.5.3
