apiVersion: v1
kind: Secret
metadata:
    name: hello-world-secret
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:jy/CfMyvj96CpuL59I4T8hfC1iWFmTmNk5cUapaKhni6sGOlfMKib4mvXjFGN7uaWdsQ6Ws=,iv:7dkSIpa3IZy4CU4NW2r74mGJe98Hg0qBCs849gOKilo=,tag:OqoH3fZIXGRj0VOTpRl00A==,type:str]
    api_key: ENC[AES256_GCM,data:9QiJKFeN0NTak2KOXBZf5q/Zsu+2,iv:drDlD6aU7YULVO9yWhXOeJk8uigBxhB0znHU48XVpw4=,tag:vgEj/lXMN8TtOmEXEoD92Q==,type:str]
sops:
    age:
        - recipient: age1u39s0c70ny5tjvvgvgj0jdw6ejxzs0t93k2tl0czmvjczt64yvjst7rkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSU1OT0lPK0dvbFcweUFO
            SVU4d0ZPanlvV3lWcEdkWE12am9VbEs2NG5zCmFCc3YzdjhuOUxPaUwvUkpta1FC
            QWJjc2NXN3B4ZXY1OGxFYWNkanlHbTgKLS0tIGdkNXN6TmM3ZHRpREdrMjN4b1Nm
            cFF6QmJRVklxYjZpUmFYUjMvYzZpRGMKfDwmBKgmz21p4nNBY53KoPKSfFQrYzMA
            y5EENjzerHeKpz94LxtCgZ9fgyq/ZDHhAWuK2t/m9843dNzDQud4mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T12:52:00Z"
    mac: ENC[AES256_GCM,data:UsCePExADvJeMgtSx5Nz84fQQRLZugyqMAeXvEh5mQHiFynQT3TYw9kDDUOLkE8SzQGl7GzTmMBO8oImaZAlLwoNHWnSDl7lukDWNZVO5sXVUUFXsNLuF9bUUQI5y2aVT8EvRqu2o14EFSknpNi2xLjvPCbmrxxhldV5+5oEgzs=,iv:uUOUIZc9P05jiKa1CfOWAYZJS3cv+IBgla0rvKnFM20=,tag:ZZzfQIv7QywTHL1c3hk/Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
