apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - applicationset.yaml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.1.3
    releaseName: argocd
    namespace: argocd
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: "--enable-helm"
      ingress:
        enabled: true
        hosts:
          - argocd.localhost
        paths:
          - /
        pathType: ImplementationSpecific
